### ISSUE TITLE
Cannot reenable CSS

### ISSUE THREAD

**Issue by jimbo1qaz** [ThatOneGuyDotNet/QuickJava#28]
For some reason, I cannot reenable CSS after disabling it. I need to open a new tab in order to fix it.

Firefox Dev 45.0a2 on Windows.

**Comment by markwr** [comment]
When I click the CS Button to turn off Page Style, and later click it again to toggle Page Style back on, it does not come back on. So I have to go to the Firefox menu: View / Page Style, and then click to toggle back again from "No Style" back to "Basic Page Style". Your extension used to work properly for the CS toggle in prior versions. If you plan to fix this, fine, otherwise do you have any suggestions for me to conveniently get around this (something easier than me digging into the Firefox menus, or looking for another extension). Thanks, and have a great day.

**Comment by Gitoffthelawn** [comment]
Confirmed fixed.  Thank you!

**Comment by markwr** [comment]
Thank you!
