### ISSUE TITLE
When extension buttons in toolbar, highlight on hover is larger than other buttons

### ISSUE THREAD

**Issue by Gitoffthelawn** [ThatOneGuyDotNet/QuickJava#34]
When QuickJava buttons are placed in the main toolbar, and the cursor is placed over one of them (`:hover`), the highlighted area is larger than the area highlighted by buttons from other extensions.

**Comment by ThatOneGuyDotNet** [comment]
Unfortunately this is due to a bug in FF's display of the menu items.  My code is not the same as most plugins to enable the custom style options, however it meets all specifications for adding elements to the menus and I noticed this when I was first rewriting them.  At the time I did hours of research and testing to try to work around their bug to no avail.  Unfortunately I don't remember and didn't document which id the FF bug was reported under so I cannot provide that.

**Comment by Gitoffthelawn** [comment]
Thanks.  Glad to know you noticed it too.

Just to confirm, there was a bugzilla bug report on file, correct?

**Comment by ThatOneGuyDotNet** [comment]
I believe so.  This was a few years ago that I looked into it though so I have no hopes of ever seeing it fixed.

**Comment by Gitoffthelawn** [comment]
Thanks.  I also get frustrated with outstanding bugs not getting fixed.
